services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: loan_app
    container_name: app
    depends_on:
      - mlflow
    environment:
      APP_PORT: ${APP_PORT}
      MLFLOW_PORT: ${MLFLOW_PORT}
      MLFLOW_BASE_URI: ${MLFLOW_BASE_URI}
      HOST: ${HOST}
      PLATFORM: docker
    ports:
      - 8000:${APP_PORT}
    restart: unless-stopped

  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    image: loan_mlflow
    container_name: mlflow_server
    ports:
      - 5000:${MLFLOW_PORT}
    restart: unless-stopped
